<?php

namespace App\Http\Controllers;

use App\Models\Order;
use App\Models\Service;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    public function store(Request $request)
    {
        $request->validate([
            'items' => 'required|array|min:1',
            'items.*.service_id' => 'required|exists:services,id',
            'items.*.shoe_name' => 'required|string|max:255',
            'items.*.shoe_brand' => 'nullable|string|max:255',
            'items.*.shoe_size' => 'nullable|string|max:50',
            'items.*.shoe_material' => 'nullable|string|max:100',
            'payment_method' => 'required|string|in:QRIS,Transfer Bank,Cash',
            'notes' => 'nullable|string',
            'voucher_code' => 'nullable|string|exists:vouchers,code',
        ]);

        // Calculate total price from all items
        $totalPrice = 0;
        $itemsData = [];

        foreach ($request->items as $item) {
            $service = Service::find($item['service_id']);
            $totalPrice += $service->price;
            $itemsData[] = [
                'service_id' => $service->id,
                'shoe_name' => $item['shoe_name'],
                'shoe_brand' => $item['shoe_brand'] ?? null,
                'shoe_size' => $item['shoe_size'] ?? null,
                'shoe_material' => $item['shoe_material'] ?? null,
                'quantity' => 1,
                'price' => $service->price,
            ];
        }

        // Apply voucher if provided
        $discountAmount = 0;
        $voucherCode = null;

        if ($request->voucher_code) {
            $voucher = \App\Models\Voucher::where('code', $request->voucher_code)->where('is_active', true)->first();
            if ($voucher) {
                $voucherCode = $voucher->code;
                if ($voucher->discount_type == 'percent') {
                    $discountAmount = $totalPrice * ($voucher->discount_amount / 100);
                } else {
                    $discountAmount = $voucher->discount_amount;
                }
                
                // Ensure discount doesn't exceed total price
                if ($discountAmount > $totalPrice) {
                    $discountAmount = $totalPrice;
                }
                
                $totalPrice -= $discountAmount;
            } else {
                return back()->withErrors(['voucher_code' => 'Voucher tidak valid atau sudah tidak aktif.']);
            }
        }

        // Create the order (tracking_code is auto-generated by model)
        $order = Order::create([
            'user_id' => auth()->id(),
            'status' => 'pending',
            'total_price' => $totalPrice,
            'payment_method' => $request->payment_method,
            'payment_status' => 'unpaid',
            'voucher_code' => $voucherCode,
            'discount_amount' => $discountAmount,
            'notes' => $request->notes,
        ]);

        // Create all order items
        foreach ($itemsData as $itemData) {
            $order->items()->create($itemData);
        }

        if ($request->ajax() || $request->wantsJson()) {
            $paymentUrl = null;
            if ($order->payment_method !== 'Cash') {
                $paymentUrl = route('payment.pay', $order);
            }
            return response()->json([
                'success' => true,
                'message' => 'Pesanan berhasil dibuat!',
                'payment_url' => $paymentUrl,
                'tracking_code' => $order->tracking_code
            ]);
        }

        if ($order->payment_method !== 'Cash') {
            return redirect()->route('payment.pay', $order);
        }

        return redirect()->route('customer.dashboard')->with('status', 'Pesanan berhasil dibuat! Kode tracking Anda: ' . $order->tracking_code);
    }
}
